Resources:
  ProductSpecificationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
#        - AttributeName: createdBy
#          AttributeType: S
        - AttributeName: productSpecificationId
          AttributeType: S
      KeySchema:
#        - AttributeName: createdBy
#          KeyType: RANGE
        - AttributeName: productSpecificationId
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
